site:
  title: The Ritual Place
  url: https://docs.theritual.place
  start_page: immersive_incantations::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/SneakyAlba/immersive_incantations
    branches: docs
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
